mod.id = "mc2_interactivefoliage"
mod.name = "MC2 - Interactive Foliage"
mod.group = "net.karto.mc2"
mod.version = "1.1.0"
mod.channel_tag = ""
mod.description = "Physics-based visual interaction between entities and foliage blocks."
mod.authors = ["KartO"]
mod.contributors = ["RazorPlay01"]
mod.inception_year = "2026"
mod.license.name = "CC-BY-NC-SA-4.0"
mod.license.url = "https://github.com/RazorPlay01/CustomPlayerAnimation/blob/stonecutter/LICENSE-CC-BY-NC-SA-4.0"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/Kart0/mc2-interactivefoliage/tree/main"
mod.homepage_url = "https://github.com/Kart0/mc2-interactivefoliage/tree/main"
mod.issues_url = "https://github.com/Kart0/mc2-interactivefoliage/tree/main/issues"
mod.discord_url = ""
[[mod.pom.developers]]
id = "karto"
name = "KartO"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.2"

[fabric."1.20.1"]
deps.minecraft = "1.20.1"
deps.fabric-api = "0.92.7+1.20.1"
deps.sway = "iZviZU5a"
deps.modmenu = "7.2.2"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.7+1.21.1"
deps.sway = "mCSekHhi"
deps.modmenu = "11.0.4"

[fabric."1.21.11"]
deps.minecraft = "1.21.11"
deps.fabric-api = "0.141.3+1.21.11"
deps.sway = "1zOfdCYW"
deps.modmenu = "17.0.0"
publish.additionalVersions = ["1.21.10"]

[fabric."26.1.2"]
deps.minecraft = "26.1.2"
deps.fabric-api = "0.146.1+26.1.2"
deps.sway = "qr3s6iO6"
deps.modmenu = "18.0.0-alpha.8"
publish.additionalVersions = ["26.1.1", "26.1"]

[forge]

[forge."1.20.1"]
deps.minecraft = "1.20.1"
deps.forge = "47.4.10"

[neoforge]

[neoforge."1.21.1"]
deps.minecraft = "1.21.1"
deps.neoforge = "21.1.213"
deps.sway = "Fxgc0o4R"

[neoforge."1.21.11"]
deps.minecraft = "1.21.11"
deps.neoforge = "21.11.42"
deps.sway = "yCg9q6sZ"
publish.additionalVersions = ["1.21.10"]

[neoforge."26.1.2"]
deps.minecraft = "26.1.2"
deps.neoforge = "26.1.2.29-beta"
deps.sway = "ylZqZ7YV"
publish.additionalVersions = ["26.1.1", "26.1"]
